"""Chatbot blueprint: /api/chatbot/* endpoints."""
import json
import logging
from flask import Blueprint, request, jsonify, send_file, render_template
from flask_login import login_required, current_user

from models import db, ChatbotConfig
from app_pkg.chatbot.providers import get_provider
from app_pkg.chatbot.tools import (
    get_tools_for_role, get_system_prompt, get_suggestions, is_tool_allowed
)
from app_pkg.chatbot.actions import execute_tool
from app_pkg.chatbot import file_manager

logger = logging.getLogger('sistema_academico')

chatbot_bp = Blueprint('chatbot', __name__)


def _get_user_role(user):
    """Determine the primary role string for tool access."""
    if user.is_admin():
        return 'admin'
    elif user.is_jefe_carrera():
        return 'jefe_carrera'
    elif user.rol == 'profesor_completo':
        return 'profesor_completo'
    else:
        return 'profesor_asignatura'


@chatbot_bp.route('/api/chatbot/message', methods=['POST'])
@login_required
def chatbot_message():
    """Process a chat message and return the LLM response."""
    config = ChatbotConfig.get_config()

    if not config.habilitado:
        return jsonify({'error': 'El chatbot no está habilitado.'}), 403

    data = request.get_json()
    if not data or not data.get('text', '').strip():
        return jsonify({'error': 'Mensaje vacío.'}), 400

    user_text = data['text'].strip()
    history = data.get('history', [])

    role = _get_user_role(current_user)
    system_prompt = get_system_prompt(role)
    tools = get_tools_for_role(role)

    # Build messages
    messages = [{'role': 'system', 'content': system_prompt}]
    for msg in history[-20:]:  # Limit history
        messages.append({
            'role': msg.get('role', 'user'),
            'content': msg.get('content', '')
        })
    messages.append({'role': 'user', 'content': user_text})

    try:
        provider = get_provider(config.provider, **config.get_provider_kwargs())
    except Exception as e:
        logger.error(f"Error creando provider LLM: {e}")
        return jsonify({'error': f'Error de configuración del LLM: {str(e)}'}), 500

    try:
        response = provider.chat(messages, tools=tools if tools else None)
    except Exception as e:
        logger.error(f"Error en LLM chat: {e}")
        return jsonify({'error': f'Error del servicio LLM: {str(e)}'}), 500

    # Process tool calls if any
    result_html = None
    download_url = None

    if response.tool_calls:
        for tc in response.tool_calls:
            if not is_tool_allowed(role, tc.name):
                response.text = f'No tienes permisos para ejecutar la acción "{tc.name}".'
                break

            tool_result = execute_tool(tc.name, tc.arguments, current_user)

            # Send tool result back to LLM for natural language response
            tool_result_text = tool_result['text']
            if tool_result.get('html'):
                result_html = tool_result['html']
            if tool_result.get('download_url'):
                download_url = tool_result['download_url']

            # Add tool result to messages and get final response
            messages.append({'role': 'assistant', 'content': response.text or f'Ejecutando {tc.name}...'})
            messages.append({'role': 'user', 'content': f'[Resultado de {tc.name}]: {tool_result_text}'})

            try:
                final_response = provider.chat(messages)
                response.text = final_response.text
            except Exception as e:
                logger.error(f"Error en segunda llamada LLM: {e}")
                response.text = tool_result_text

            break  # Process only the first tool call

    return jsonify({
        'text': response.text,
        'html': result_html,
        'download_url': download_url,
    })


@chatbot_bp.route('/api/chatbot/download/<file_id>')
@login_required
def chatbot_download(file_id):
    """Download a file generated by the chatbot."""
    info = file_manager.get_file(file_id, current_user.id)
    if not info:
        return jsonify({'error': 'Archivo no encontrado o expirado.'}), 404

    return send_file(
        info['path'],
        as_attachment=True,
        download_name=info['filename'],
        mimetype=info['mimetype'],
    )


@chatbot_bp.route('/api/chatbot/config', methods=['GET', 'POST'])
@login_required
def chatbot_config():
    """Admin panel for chatbot configuration."""
    if not current_user.is_admin():
        return jsonify({'error': 'Acceso denegado.'}), 403

    if request.method == 'GET':
        return render_template('admin/chatbot_config.html')

    # POST - save config
    data = request.get_json() if request.is_json else request.form
    config = ChatbotConfig.get_config()

    config.provider = data.get('provider', config.provider)
    config.model_name = data.get('model_name', config.model_name)
    config.habilitado = data.get('habilitado', 'false') in (True, 'true', 'on', '1')
    config.max_tokens = int(data.get('max_tokens', config.max_tokens))
    config.temperatura = float(data.get('temperatura', config.temperatura))

    # Only update api_key if provided (don't clear it)
    api_key = data.get('api_key', '').strip()
    if api_key:
        config.api_key = api_key

    ollama_url = data.get('ollama_url', '').strip()
    if ollama_url:
        config.ollama_url = ollama_url

    db.session.commit()

    if request.is_json:
        return jsonify({'success': True, 'message': 'Configuración guardada.'})

    from flask import flash, redirect, url_for
    flash('Configuración del chatbot guardada.', 'success')
    return redirect(url_for('chatbot.chatbot_config'))


@chatbot_bp.route('/api/chatbot/test', methods=['POST'])
@login_required
def chatbot_test():
    """Test the LLM connection with current config."""
    if not current_user.is_admin():
        return jsonify({'error': 'Acceso denegado.'}), 403

    config = ChatbotConfig.get_config()

    try:
        provider = get_provider(config.provider, **config.get_provider_kwargs())
        result = provider.test_connection()
        return jsonify(result)
    except Exception as e:
        return jsonify({'success': False, 'message': str(e)})


@chatbot_bp.route('/api/chatbot/suggestions')
@login_required
def chatbot_suggestions():
    """Get suggestion chips for the current user's role."""
    role = _get_user_role(current_user)
    return jsonify({'suggestions': get_suggestions(role)})


@chatbot_bp.route('/api/chatbot/status')
@login_required
def chatbot_status():
    """Check if chatbot is enabled. Admins get full config details."""
    config = ChatbotConfig.get_config()
    data = {
        'habilitado': config.habilitado,
        'provider': config.provider,
    }
    if current_user.is_admin():
        data.update({
            'model_name': config.model_name,
            'ollama_url': config.ollama_url or 'http://localhost:11434',
            'max_tokens': config.max_tokens,
            'temperatura': config.temperatura,
            'has_api_key': bool(config.api_key),
        })
    return jsonify(data)
